name:                gameEngine
version:             0.1.0.0
github:              "githubuser/gameEngine"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/gameEngine#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- lens
- linear
- StateVar
- random
- containers
- colour
- transformers
- polysemy
- vector
- mtl
- apecs
- JuicyPixels
- massiv
- storable-tuple
- apecs-physics
- GPipe
- GPipe-GLFW
- GLFW-b
- exception-transformers
- Boolean
- cpu
- bytestring-conversion
- binary
- file-embed

default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - ExistentialQuantification
  - RankNTypes
  - GADTs
  - ScopedTypeVariables
  - TypeOperators
  - DataKinds
  - KindSignatures
  - DeriveFunctor
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - TypeApplications
  - TupleSections

library:
  source-dirs: [src]

executables:
  gameEngine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameEngine

tests:
  gameEngine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - gameEngine
