name:                haskell-game
version:             0.1.0.0
github:              "Simre1/haskell-game"
license:             MIT
author:              "Simre"
copyright:           "2019 Simre"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/gameEngine#readme>

dependencies:
- base >= 4.7 && < 5
- text
- linear
- random
- polysemy
- polysemy-plugin
- vector
- apecs
- JuicyPixels
- apecs-physics
- GPipe
- GPipe-GLFW
- Boolean


library:
  source-dirs: [src]

executables:
  haskell-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - haskell-game
