resolver: lts-13.27

packages:
- .


extra-deps:
- chiphunk-0.1.0.3
- vector-space-0.15
- polysemy-0.6.0.0
- sdl2-2.5.0.0
- first-class-families-0.5.0.0
- th-abstraction-0.3.1.0
- unagi-chan-0.4.1.0
- type-errors-0.2.0.0
- loopbreaker-0.1.1.0
- ratio-int-0.1.2
- massiv-0.3.6.0
- scheduler-1.4.1
