resolver: lts-14.5

packages:
- apecs/apecs
- apecs/apecs-physics
- GPipe-Core/GPipe-Core
- GPipe-GLFW/GPipe-GLFW
- polysemy
- polysemy/polysemy-plugin
- .


extra-deps:
- first-class-families-0.5.0.0
- th-abstraction-0.3.1.0
- type-errors-0.2.0.0
- type-errors-pretty-0.0.0.0
- unagi-chan-0.4.1.2
